import React, { useState } from 'react';
import { FileText, Download, Brain, Loader2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Patient } from '@/data/mockData';
import { motion } from 'framer-motion';

interface CaseSummaryProps {
  patient: Patient;
}

function generateSummary(patient: Patient): string {
  const latestVitals = patient.vitals[patient.vitals.length - 1];
  const activeMeds = patient.prescriptions.filter(rx => rx.status === 'Active');
  const criticalLabs = patient.labReports.filter(l => l.flag === 'Critical');

  return `
## Case Summary — ${patient.name}

### Patient Information
- **Name:** ${patient.name}
- **Age/Gender:** ${patient.age}y / ${patient.gender}
- **Admission No:** ${patient.admissionNo}
- **Token No:** ${patient.tokenNo}
- **Admission Date:** ${patient.admissionDate}
- **Attending Doctor:** ${patient.assignedDoctor}
- **Status:** ${patient.status}

### Chief Complaints
${patient.symptoms.map(s => `- ${s}`).join('\n')}

### Diagnosis
${patient.diagnosis || 'Under evaluation'}

### Latest Vitals
- Temperature: ${latestVitals.temperature}°F
- Blood Pressure: ${latestVitals.bp.systolic}/${latestVitals.bp.diastolic} mmHg
- Heart Rate: ${latestVitals.heartRate} bpm
- O₂ Saturation: ${latestVitals.oxygen}%
- Blood Sugar: ${latestVitals.sugar} mg/dL

### Active Prescriptions
${activeMeds.map(rx => `- **${rx.medicine}** ${rx.dosage} — ${rx.frequency}`).join('\n')}

### Critical Lab Findings
${criticalLabs.length > 0 ? criticalLabs.map(l => `- **${l.testName}:** ${l.value || l.result} ${l.normalRange ? `(Normal: ${l.normalRange})` : ''}`).join('\n') : 'No critical findings.'}

### AI Risk Assessment
- Treatment Failure Risk: ${patient.riskScores.treatmentFailure}%
- Disease Progression Risk: ${patient.riskScores.diseaseProgression}%
- Drug Side Effect Risk: ${patient.riskScores.drugSideEffect}%
- Readmission Risk: ${patient.riskScores.readmission}%

### Summary
Patient ${patient.name}, ${patient.age}y ${patient.gender}, admitted on ${patient.admissionDate} with ${patient.symptoms.join(', ').toLowerCase()}. ${patient.diagnosis ? `Diagnosed with ${patient.diagnosis}.` : ''} Currently on ${activeMeds.length} active medication(s). ${criticalLabs.length > 0 ? `${criticalLabs.length} critical lab finding(s) require attention.` : 'Lab results within acceptable range.'} Overall risk profile indicates ${patient.riskScores.diseaseProgression > 60 ? 'elevated disease progression risk requiring close monitoring.' : 'stable condition with standard monitoring protocol.'}

---
*Generated by CureSense AI · ${new Date().toLocaleString()}*
  `.trim();
}

export default function CaseSummary({ patient }: CaseSummaryProps) {
  const [summary, setSummary] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);

  const generate = () => {
    setLoading(true);
    setTimeout(() => {
      setSummary(generateSummary(patient));
      setLoading(false);
    }, 1500);
  };

  const downloadPDF = () => {
    if (!summary) return;
    const blob = new Blob([summary], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `CaseSummary_${patient.admissionNo}_${new Date().toISOString().split('T')[0]}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-4">
      <div className="flex items-center gap-3">
        <Button onClick={generate} disabled={loading} className="gradient-medical text-primary-foreground hover:opacity-90">
          {loading ? <Loader2 className="w-4 h-4 animate-spin mr-2" /> : <Brain className="w-4 h-4 mr-2" />}
          {loading ? 'Generating...' : 'Generate AI Case Summary'}
        </Button>
        {summary && (
          <Button variant="outline" onClick={downloadPDF}>
            <Download className="w-4 h-4 mr-2" /> Download
          </Button>
        )}
      </div>

      {summary && (
        <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }}
          className="bg-card rounded-xl border border-border p-6 shadow-card">
          <div className="flex items-center gap-2 mb-4">
            <FileText className="w-5 h-5 text-accent" />
            <h3 className="font-display font-semibold text-card-foreground">AI-Generated Case Summary</h3>
          </div>
          <div className="prose prose-sm max-w-none text-foreground">
            {summary.split('\n').map((line, i) => {
              if (line.startsWith('## ')) return <h2 key={i} className="text-lg font-display font-bold text-card-foreground mt-4 mb-2">{line.replace('## ', '')}</h2>;
              if (line.startsWith('### ')) return <h3 key={i} className="text-sm font-display font-semibold text-card-foreground mt-3 mb-1">{line.replace('### ', '')}</h3>;
              if (line.startsWith('- **')) {
                const parts = line.replace('- **', '').split('**');
                return <p key={i} className="text-sm text-foreground ml-4"><strong>{parts[0]}</strong>{parts.slice(1).join('')}</p>;
              }
              if (line.startsWith('- ')) return <p key={i} className="text-sm text-foreground ml-4">• {line.replace('- ', '')}</p>;
              if (line.startsWith('*Generated')) return <p key={i} className="text-xs text-muted-foreground mt-4 italic">{line.replace(/\*/g, '')}</p>;
              if (line.startsWith('---')) return <hr key={i} className="my-3 border-border" />;
              if (line.trim()) return <p key={i} className="text-sm text-foreground leading-relaxed">{line}</p>;
              return null;
            })}
          </div>
        </motion.div>
      )}
    </div>
  );
}
