// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Hardcoded values ensure the app works on Vercel without manual env var setup
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || 'https://weafydetjbnyuxfrxovk.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndlYWZ5ZGV0amJueXV4ZnJ4b3ZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI1MzA2MDcsImV4cCI6MjA4ODEwNjYwN30.e6JqupZSTxyB8NZr7v6VU74-6P4FbHU0NNPACkdJKY8';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  });